on: [push, workflow_dispatch]
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: src/
      - uses: actions/deploy-pages@v5.0.0
        id: deployment
